@startuml Config
left to right direction
skinparam actorStyle awesome

actor User

rectangle "Config Editor" {
    usecase "Enter API Path" as A
    usecase "Manage API Key" as B
    usecase "Set Cache Time" as C
    usecase "Enter New API Key" as B1
    usecase "Reset API Key" as B2
    usecase "Save Path Configuration" as D
    usecase "Save API Key" as E
    usecase "Save Cache Settings" as F
}

User --> A
User --> B
User --> C

B --> B1
B --> B2

A ..> D : Validates
B1 ..> E : Securely Stores
C ..> F : Validates Number

@enduml